### ISSUE TITLE
Copied code

### ISSUE THREAD

**Issue by mperham** [nickelser/zhong#14]
Oops

Looks like you lifted a significant amount of LGPL code from Sidekiq. You will need to rewrite that code or relicense as LGPL.

**Comment by mperham** [comment]
Oops

Looks like you lifted a significant amount of LGPL code from Sidekiq. You will need to rewrite that code or relicense as LGPL.

**Comment by nickelser** [comment]
@mperham I definitely remember looking at Sidekiq code for some of the Redis handling stuff, but, most of this was written over a year ago -- could you please advise specifically which sections of code you are referencing?

I have no real problem with re-licensing the library as LGPL -- what would you recommend? I am happy to contribute back any changes I made that could be useful to Sidekiq, as well (and thank you again for your hard work on that project!).

**Comment by nickelser** [comment]
(FWIW the project upon which this was based and is roughly compatible with was (Clockwork)[https://github.com/Rykian/clockwork], just for another point of comparison)

**Comment by mperham** [comment]
web.rb and web_helpers.rb are essentially older copies of Sidekiq code, including comments I wrote myself.

https://github.com/nickelser/zhong/blob/master/lib/zhong/web_helpers.rb
https://github.com/nickelser/zhong/blob/master/lib/zhong/web.rb#L73

I prefer to use LGPL licensing for my OSS, as it ensures no one else can create a closed source fork of my project but YMMV.  If you want to keep that code, just relicense.  Otherwise, delete those files and reimplement from scratch.

**Comment by nickelser** [comment]
@mperham sorry about that -- I've gone back, added attribution, and [re-licensed the project](https://github.com/nickelser/zhong/pull/15).

Let me know if you have any other feedback or suggestions, and many apologies for lifting that code without proper licensing. That was a mistake and oversight on my part!

**Comment by mperham** [comment]
Thanks for being super chill about the whole thing!
