### ISSUE TITLE
Incomplete documentation.

### ISSUE THREAD

**Issue by j3pic** [nickelser/zhong#19]
The `README.md` to this project suggests that all you have to do is set up Redis, evaluate a `Zhong.schedule` call, and boom! the job happens as specified. But there is a missing step.

For example, I ran the following in a Rails console running Instacart's own `catalog` app, which uses Zhong in production. If Zhong "just works" with no configuration whatsoever, evaluating the following should result in a string being printed to the terminal every second:

```
Zhong.schedule do
  every 1.seconds, 'This should do something' do
    puts 'Hello!'
  end
end
```

Instead of seeing *anything* printed to STDOUT, that expression just returns some object and does nothing else.

Zhong does absolutely nothing until the following is evaluated from somewhere:

```
Zhong.start
```

There is a `bin/zhong` script included with this Gem that does almost nothing but this.

**Comment by nickelser** [comment]
@j3pic thanks for the issue! @AntoineAugusti tackled this in #21
