### ISSUE TITLE
Scheduled jobs at specific times while system is down

### ISSUE THREAD

**Issue by joevandyk** [nickelser/zhong#30]
Say I have a job scheduled to run at 3 am each night. And for whatever reason, there's not a running Ruby process at exactly 3 am -- say it stops at 2:59 and resumes at 3:01.

Does zhong provide a way to automatically run that 3 am job if that scenario were to happen?

**Comment by nickelser** [comment]
it should be run (i think there is a grace period of 15 minutes). is that not the case?
